services:
  api:
    build: ./app
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=test_db
      - HOST=db
      - USER=postgres
    ports:
      - "5005:5000"
    depends_on:
      - db  
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=test_db
    volumes:
      - data-psgs:/var/lib/postgresql/data
volumes:
  data-psgs: